AgnostiqHQ/covalent-braket-plugin

- CHANGELOG.md
- covalent_braket_plugin/scripts.py
> remove covalent prerelease from docker image

- CHANGELOG.md
- covalent_braket_plugin/braket.py
- requirements.txt
- setup.py
- tests/covalent_braket_plugin_tests/braket_test.py
- tests/requirements.txt
Closes #16.
Run sync methods in threadpool for now.
> Use awsexecutor

- CHANGELOG.md
- covalent_braket_plugin/braket.py
- tests/covalent_braket_plugin_tests/braket_test.py
> Getting default values from config file when instantiating class

- CHANGELOG.md
- setup.py
> Update environment variable setting

- .github/workflows/license.yml
- CHANGELOG.md
> Push license yml fix

- CHANGELOG.md
- README.md
> README update to include ecr_image_uri 

- CHANGELOG.md
- requirements.txt
> Bumped aws plugins version to new stable release

- CHANGELOG.md
- pyproject.toml
- tests/functional_tests/README.md
- tests/functional_tests/basic_quantum_workflow_test.py
- tests/functional_tests/basic_workflow_test.py
- tests/functional_tests/fixtures/executor.py
> Updated functional tests to use pytest read from .env file

- .env.example
- CHANGELOG.md
- covalent_braket_plugin/braket.py
> Not setting default values for aws boto session args

- .github/workflows/docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Dockerfile
> add executor docker image build workflow

- .github/workflows/docker.yml
- CHANGELOG.md
> Added id-token write permission for OIDC for pushing to ECR (docker workflow)

- .github/workflows/docker.yml
- CHANGELOG.md
- Dockerfile
> Updated docker workflow to specify pre-release flag as a build arg

- .github/workflows/docker.yml
- CHANGELOG.md
> Docker workflow follow up - Allow manual pre-releases

- .github/workflows/tests.yml
- CHANGELOG.md
> Tests workflow fix

- .github/workflows/docker.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Fix test workflow

- CHANGELOG.md
- tests/functional_tests/basic_quantum_workflow_test.py
- tests/functional_tests/basic_workflow_test.py
> Add print statements to functional tests

- .github/workflows/docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
> Configurable covalent version in docker workflow

- .github/workflows/docker.yml
- CHANGELOG.md
> Fixed `docker` workflow referring to deprecated `stable_version` input

- CHANGELOG.md
- covalent_braket_plugin/braket.py
- tests/covalent_braket_plugin_tests/braket_test.py
> [UnitaryHack] Add Task Cancellation Braket Job

- .flake8
- .github/workflows/changelog.yml
- .github/workflows/changelog_reminder.yml
- .github/workflows/docker.yml
- .github/workflows/license.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .github/workflows/version.yml
- .gitignore
- .pre-commit-config.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- LICENSE
- README.md
- covalent_braket_plugin/braket.py
- pyproject.toml
- setup.py
- tests/covalent_braket_plugin_tests/braket_test.py
- tests/covalent_braket_plugin_tests/exec_test.py
> updating license

- .gitignore
- CHANGELOG.md
- Dockerfile
- MANIFEST.in
- covalent_braket_plugin/assets/infra/main.tf
- covalent_braket_plugin/assets/infra/outputs.tf
- covalent_braket_plugin/assets/infra/variables.tf
- covalent_braket_plugin/assets/infra/versions.tf
> Fixing docker image and adding tf files
